#!/usr/bin/env python3
"""Build languages/el.po, el.mo and el.l10n.php from tools/el.py.
Fails if a theme string has no Greek translation."""
import json, os, struct, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))
from el import EL  # noqa: E402

strings = json.loads(subprocess.check_output([sys.executable, os.path.join(ROOT, 'tools', 'extract-strings.py')]))
missing = [s for s in strings if s not in EL]
if missing:
    sys.exit('Missing Greek translations:\n  ' + '\n  '.join(m.replace('\x04', ' | ').replace('\x00', ' / ') for m in missing))

HEADER = ('Project-Id-Version: Beleon Tours\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\n'
          'Content-Transfer-Encoding: 8bit\nLanguage: el\nPlural-Forms: nplurals=2; plural=(n != 1);\n')

def mo_entries():
    out = {'': HEADER}
    for key in strings:
        val = EL[key]
        out[key] = '\x00'.join(val) if isinstance(val, tuple) else val
    return out

# .mo (GNU gettext binary)
entries = sorted(mo_entries().items())
ids = b''.join(k.encode() + b'\0' for k, _ in entries)
strs = b''.join(v.encode() + b'\0' for _, v in entries)
n = len(entries)
koff = 7 * 4 + 16 * n
voff = koff + len(ids)
ktab, vtab, o1, o2 = [], [], 0, 0
for k, v in entries:
    kb, vb = k.encode(), v.encode()
    ktab += [len(kb), koff + o1]; o1 += len(kb) + 1
    vtab += [len(vb), voff + o2]; o2 += len(vb) + 1
mo = struct.pack('Iiiiiii', 0x950412de, 0, n, 7 * 4, 7 * 4 + n * 8, 0, 0) + struct.pack('%di' % (2 * n), *ktab) + struct.pack('%di' % (2 * n), *vtab) + ids + strs
open(os.path.join(ROOT, 'languages', 'el.mo'), 'wb').write(mo)

# .l10n.php (WordPress 6.5+ fast translation format)
def php(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"
def phpk(s):  # keys may contain \x04 / \x00: use double quotes with escapes
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('$', '\\$').replace('\x04', '\\4').replace('\x00', '\\0') + '"'
msgs = []
for key in strings:
    val = EL[key]
    k = key.split('\x00')[0]
    v = '\x00'.join(val) if isinstance(val, tuple) else val
    msgs.append('\t\t' + phpk(k) + ' => ' + phpk(v) + ',')
open(os.path.join(ROOT, 'languages', 'el.l10n.php'), 'w', encoding='utf-8').write(
    "<?php\n// Generated by tools/build-i18n.py from tools/el.py. Do not edit.\nreturn array(\n"
    "\t'project-id-version' => 'Beleon Tours',\n\t'language' => 'el',\n\t'plural-forms' => 'nplurals=2; plural=(n != 1);',\n"
    "\t'messages' => array(\n" + '\n'.join(msgs) + "\n\t),\n);\n")

# .po (for Poedit / Loco Translate)
def po(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n') + '"'
lines = ['msgid ""', 'msgstr ""'] + [po(l + '\n') for l in HEADER.strip().split('\n')] + ['']
for key in strings:
    val = EL[key]
    ctx = None
    if '\x04' in key:
        ctx, key = key.split('\x04', 1)
    if ctx:
        lines.append('msgctxt ' + po(ctx))
    if '\x00' in key:
        s1, s2 = key.split('\x00')
        lines += ['msgid ' + po(s1), 'msgid_plural ' + po(s2), 'msgstr[0] ' + po(val[0]), 'msgstr[1] ' + po(val[1]), '']
    else:
        lines += ['msgid ' + po(key), 'msgstr ' + po(val), '']
open(os.path.join(ROOT, 'languages', 'el.po'), 'w', encoding='utf-8').write('\n'.join(lines))
print('Built %d Greek strings.' % len(strings))
